### ISSUE TITLE
Using this library for kubernetes authentication - Example

### ISSUE THREAD

**Issue by alok87** [coreos/go-oidc#197]
Kubernetes authentication can be done using Google as the OIDC provider. Below is configuration for the user.
```
users:
- name: you@yourdomain.com
  user:
    auth-provider:
      name: oidc      
      config:
        client-id: <client-id>
        client-secret: <client-secret>
        idp-issuer-url: https://accounts.google.com        
        id-token: <id-token>
        refresh-token: <refresh-token>
```

I was able to get the `idToken` using the example mentioned in this repo. But the token response does not have any `refreshToken`

How can we get the `refreshToken` and `idToken` using this library for use in kubernetes.

This is how oidc helper written here does it - https://github.com/micahhausler/k8s-oidc-helper/blob/master/internal/helper/helper.go#L45-L65

I wanted to use this well maintained library to avoid making api requests on my own. Please suggest.
