### ISSUE TITLE
Get JWT iDToken string instead of go-oidc object

### ISSUE THREAD

**Issue by alok87** [coreos/go-oidc#198]
[Verify](https://godoc.org/github.com/coreos/go-oidc#IDTokenVerifier.Verify) returns a IDToken object. Need a string as kubernetes authentication for OIDC requires a idToken as string. Please suggest how to do that.

```
users:
- name: you@yourdomain.com
  user:
    auth-provider:
      name: oidc      
      config:
        client-id: <client-id>
        client-secret: <client-secret>
        idp-issuer-url: https://accounts.google.com        
        id-token: <id-token>
        refresh-token: <refresh-token>
```
